### ISSUE TITLE
dmd complains about missing function

### ISSUE THREAD

**Issue by ell1e** [epi/ext4rescue#5]
dmd complains about a missing function when trying to build ext4rescue:

> `source/extract.d(103,9): Error: module `core.sys.posix.unistd` import `lchown` not found, did you mean function `core.sys.posix.unistd.chown`?`

Is there any chance this program is still maintained and will be possibly updated? I'm assuming my version of D and dmd might be too new. I'm using DMD64 D Compiler v2.109.1.

**Comment by epi** [comment]
Hi, I made this tool long time ago just to rescue some private data from a failed HDD of mine, but let's try to see if it can still be useful. :)

What OS/libc are you building for?
`lchown` seems to be declared in `unistd.d` in v2.109.1 for multiple environments: `CRuntime_Glibc`, `Darwin`, `FreeBSD`, `NetBSD`, `OpenBSD`, `DragonFlyBSD`, `CRuntime_Bionic`, `Solaris` and `CRuntime_UClibc`. Are you maybe building with `CRuntime_Musl` or some other variant?

**Comment by ell1e** [comment]
I'm on Alpine Linux, so if it was `CRuntime_Musl` that would make sense! I know nothing about D though, I installed it from the Alpine repositories.

**Comment by epi** [comment]
Added a quick workaround in c900228. Can you check if it builds now?

**Comment by ell1e** [comment]
Can confirm that on Alpine, after using `apk add libguestfs libguest-fs-dev --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/` (warning, i assume installing stuff from a temporary extra repo like that could potentially break things and lead to conflicts) since libguestfs doesn't seem to be in the main repository, it compiles fine:

```
$ make
dub build
    Starting Performing "debug" build using /usr/bin/dmd for x86_64.
    Building ext4rescue ~master: building configuration [application]
     Linking ext4rescue
$
```

**Comment by epi** [comment]
Thanks!

I must get rid of libguestfs anyway. It's used only in tests and on some distros breaks due to kernel image not being readable by non-root users.
